# Go To Jekyll
title: LPFP Le Petit Fab-Lab de Paris
description: >
  Petit Fab-Lab de Paris
  description du site

logo: /assets/img/LPFP_square_logo.png
favicon: /assets/img/favicon.ico
email: bonjour (at) lepetitfablabdeparis.fr

baseurl: /fablab
url: ""

# GitHub
github_username: LPFP
# repository: LPFP/LPFP.github.io

author:
  name: Asso [Fab-Lab]
  email: service@lepetitfablabdeparis.fr
  adr: 86 Avenue Philippe Auguste 75011 Paris
  tel: +33 9 51 58 75 50
  uri: https://rroubin.fr
  twitter: remstw

timezone: Europe/Paris

social:
  twitter: https://twitter.com/lpfablabparis
  github: https://www.github.com/LPFP
  facebook: https://facebook.com/lepetitfablabdeparis

# Mailchimp infolettre
mc:
  cname: lepetitfablabdeparis
  domain: us14
  list_id: acbb278cdd
  hash: a1e7a5338e44ee5aea22927a9

token:
  mapbox: pk.eyJ1IjoibHBmcCIsImEiOiJjaXVuODhicTgwMDFrMnltaDNjcTFkZTdkIn0.AYCUkKPZjBA0uUtAgr4utw
  mapillary: MjNrd04tNVh0NXlyaU42UW1oVXdodzo3Mzc4MTk0MmM0MjJhODk4

mly_pkey: qTfbBM92Wrx2LNELoprtXw
mlatlng: [48.855000, 2.391934]
zoom: 17

# Build settings
jquery: 3.1.1.min.js
fa: 4.7.0

permalink: pretty
sass:
  style: :compressed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: true
gems:
  # - jekyll-feed
  - jemoji
  # - jekyll-gist
  # - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .sass-cache
